name: myapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  audioplayers: ^6.1.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"
  min_sdk_android: 16


flutter:
  uses-material-design: true
  assets:
    - images/mentalhealt.jpg
    - images/PROFILE.jpeg
    - images/download.png
    - images/welcome.png
    - images/lupasandi.png
    - images/verifikasi.png
    - assets/sound/musik.mp3
